### ISSUE TITLE
systemd presets not getting evaluated

### ISSUE THREAD

**Issue by dustymabe** [cgwalters/fedora-coreos-config#3]
seems like the same issue as: https://github.com/openshift/os/issues/243 - for example:

```
[root@localhost grub.d]# systemctl status coreos-firstboot-complete.service 
● coreos-firstboot-complete.service - Mark boot complete
   Loaded: loaded (/usr/lib/systemd/system/coreos-firstboot-complete.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
     Docs: https://github.com/coreos/ignition
```

This was built with the rpms from FAHC:

```
sh-4.4$ rpm -q rpm-ostree ostree
rpm-ostree-2018.7.32-961482f088e5088230935ffd7b1a094e764835db.1f289f2410d7b49abdbf6eeaf2589c3df9b642e0.fc28.x86_64
ostree-2018.8.6-a70d2f67310bd869c6a40c4013dc51a3e2f2d2a8.5bb0359caf4facc535ee3ee8b5ec7c552637c28d.fc28.x86_64
```

**Comment by cgwalters** [comment]
There were actually *two* independent bugs here:

 - We were missing `machineid-compat: false` https://github.com/cgwalters/fedora-coreos-config/commit/a80534a0ff562aaa1e6d1b329956c3e2f86e7bd9
 - For that specific unit, we were missing a preset https://github.com/cgwalters/fedora-coreos-config/commit/2b709df651fb93f6cea250a7c5d3d7dd3af48a30
